### ISSUE TITLE
ul.items is a very baaaaad idea!

### ISSUE THREAD

**Issue by tvdeyen** [revsystems/jQuery-SelectBox#10]
I made a fork an will correct some issues. I gonna append the o.selectboxClass class to the ul you create for the values. Maybe I find a fix for the wrongly calulated width of the container div as well.

**Comment by revsystems** [comment]
Yeah, that selectbox class should definitely be applied to it.

Which issue are you talking about for wrong container div width? Can you show me an example?

Thanks for the fork

**Comment by tvdeyen** [comment]
You are setting the width of the container div always to the width of the widest value. What is wrong in my opinion. The container div never gets displayed and the a.display in it has the correct width and because your ul.items are not inside the container div the div has no need for this. It should have the width of the original select element, not the option elements. I just try to find the line of code where you calculating the width for the div element. Maybe you have hint for me? :)

**Comment by revsystems** [comment]
Widths are set around lines 100-113 (for the wrapper div) and 276 (for the dropdown when positioning).

Do note that jquery-sb is intentionally set up to ignore the original size of the select element. This is done so that the width can be dynamic based on complex markup and padding in the items or display. A lot of existing selectbox plugins forced widths, and I wanted to avoid that for this one.

What is the resulting issue you're running into? Maybe there's a simpler solution that would work in the existing framework.

**Comment by tvdeyen** [comment]
Thanks. I set up an example. And now my issues are gone. Strange, should be a problem with my original markup. You can see the example here:

https://gist.github.com/779759

My issue was that the container div was far too long.

**Comment by revsystems** [comment]
Ah, okay.

Let me know if you run into any more issues and I'll try to help. I will be making some changes over the weekend too, so setting up fixed widths should be more straightforward.

Thanks

**Comment by tvdeyen** [comment]
Thank you for this great plugin and your fast help. Have a nice weekend!
