### ISSUE TITLE
Duplicate Selectbox being created.

### ISSUE THREAD

**Issue by Chris-Rouxel** [revsystems/jQuery-SelectBox#12]
We are attempting to use jQuery-SelectBox in Joomla and no matter what we are trying a duplicate Select box is being created next to the original.

We are using Joomla / Zoo / Mootools and regardless of Jquery in noconflict mode and/or Mootools disabled keep getting this duplicate.

Example at http://megaman.juiceapps.co.uk

**Comment by revsystems** [comment]
Hi,

The following code fixed the issue (the correct number of selects) in my test in Chrome:

jQuery(".selectbox.sb").trigger("destroy").filter(":last").remove();
jQuery("select").sb()

Note that this might not be any help to you--it's just something I performed as a test.

I'm not sure exactly what the cause of your problem is, but I've personally only seen this behavior when I accidentally call sb() twice on the same select. I see you only have it once in the page's source, but are there any scripts that could possibly be calling it again?

Another possibility is maybe $(document).ready() is being triggered twice. I'm not sure why that would happen, but maybe some framework triggers "ready" again?

In any case, I think it shouldn't create duplicates even if it's called multiple times, so this is a bug. I should have a fix for it up later today.

**Comment by revsystems** [comment]
Turned out to be a pretty quick fix, I think. Updated jquery.sb.js and jquery.sb.min.js. Hopefully that should fix your issue.

**Comment by revsystems** [comment]
Also, I see you're trying to setup a fixed width for your select box. Please check out the Readme for information on how to set this up correctly. You should be setting a width on both the display and the dropdown, and signalling a fixed width sb in the javascript: $("select").sb({ fixedWidth: true }).

**Comment by revsystems** [comment]
Looks like you got it working, gonna close.

Thanks for the report.

**Comment by Chris-Rouxel** [comment]
Yes, Works a treat!! thanks for the prompt reply and fix.

Chris - Juice Media
