### ISSUE TITLE
parseInt on margin-left: auto in positionSB

### ISSUE THREAD

**Issue by nicholasdavison** [revsystems/jQuery-SelectBox#17]
This has changed very slightly in your latest check in but the same issue seems to remain:

Inside positionSB() you have

var bodyX = $().jquery < "1.4.2" ? $("body").offset().left : parseInt($("body").css("margin-left"));

If running the latest jQuery, it uses parseInt($("body").css("margin-left"))

$("body").css("margin-left") can end up returning "auto"

This returns a NaN in the parseInt

This then throws NaNs through the following $dd.css({...});

Which crashes out in IE.

**Comment by revsystems** [comment]
I'll take a look--I think I came up with a solution in jQuery-inPixels, but I don't want to include that whole thing in jQuery-SelectBox. Thanks for the report. Shouldn't be long before a fix hopefully.

**Comment by revsystems** [comment]
Hi,

I just pushed a version that hopefully fixes the behavior. Let me know if it's working for you. I tested in Firefox, Chrome, and IE7-9 with jQuery 1.4.2 and 1.3.2. My test page is here:

http://dl.dropbox.com/u/124192/websites/selectbox/margin-auto.html

It incorporates part of jQuery-inPixels as well as some additional logic to account for different offsetFrom values across jQuery versions.

This bug is terrible. It seems like all the browsers handle body positioning differently. I almost want to just leave it alone and tell everyone not to use margin:auto on body.

**Comment by revsystems** [comment]
I created a separate branch "margin-auto-hack" with the version I made yesterday. However, it includes a lot of extra code which is inelegant and liable to break across different versions of jQuery and browsers.

Therefore, I decided it wasn't jQuery-SelectBox's place to "fix" this issue. Instead I will update the README in the master branch to explain it and give tips on how to avoid it.

Thanks
