### ISSUE TITLE
Couple of implementation issues

### ISSUE THREAD

**Issue by dwavell** [revsystems/jQuery-SelectBox#2]
Firstly I have quite a long selectbox using the following code:

```
    <select name="location" id="Items5">
                    <option value="0" selected="selected">Select Location</option>
                        <optgroup label="Select an Area">
                            <option value="North">North Wight</option>
                            <option value="East">East Wight</option>
                            <option value="South">South Wight</option>
                            <option value="West">West Wight</option>
                        </optgroup>
                        <optgroup label="Select Town or Village">
                            <option value="Adgestone">Adgestone</option>
                            <option value="Alverstone">Alverstone</option>
                            <option value="Apse Heath">Apse Heath</option>
                            <option value="Arreton">Arreton</option>
                            <option value="Bembridge">Bembridge</option>
                            <option value="Binstead">Binstead</option>
                            <option value="Bonchurch">Bonchurch</option>
                            <option value="Brading">Brading</option>
                            <option value="Brighstone">Brighstone</option>
                            <option value="Calbourne">Calbourne</option>
                            <option value="Carisbrooke">Carisbrooke</option>
                            <option value="Chale">Chale</option>
                            <option value="Chale Green">Chale Green</option>
                            <option value="Chillerton">Chillerton</option>
                    </optgroup>
             </select>
```

There are usually more options but have removed some to make this shorter.  The problem is when the list opens up...firstly it goes upwards rather than down which is a bit odd as it's just above the middle of the page.  But the main issue is the first selected item seems to end up at the bottom of the list so it loads with that selected but with the last items from the list next to it rather than the first itmes on the list.  any ideas?

Also, I've set the width of my selectboxes so they all look the same no matter what the content is using the .selectbox .display item in the css width setting.  This works fine, but I have 2 selectboxes that I'd like to be a different width.  Is there a better way to force the width of all my select boxes? something I can pass into the function as each box is initialised?

Many thanks,

Dan

**Comment by revsystems** [comment]
Hi Dan,

Thanks for the report. I just pushed a fix for the optgroup/option ordering. It was adding all optgroups before options, which is why yours appeared last. There was also a width issue (if the optgroups were the longest item, they'd wrap--they should have been included in the initial calculation), which should now be fixed.

Without seeing your page, I'm going to guess the selectbox going up behavior is actually functioning correctly, but maybe a little non-intuitively. If the dropdown is long enough to scroll (that is, it would go off the page), it is displayed with as much height as possible--if there is more height above the dropdown, it will display there, even if the difference is small.

I'm open to suggestions to dealing with this... maybe there should be some difference threshold option, i.e. only append above if there are 300 more pixels available up there.

For your last question, you can simply add a class onto the "select" element in question. All classes on the select element will be added to the new markup. So you could do something like .my_class.selectbox .display{} or .my_class.items{}. Refer to the .round_sb class in the example, as this is how it works.

Let me know if this helps.

**Comment by revsystems** [comment]
Just noticed something missing with direction-setting too, so maybe you were just experiencing a bug where it opened above and moved. I'm not sure exactly what you experienced, but let me know if the new code fixes it.

Thanks

**Comment by dwavell** [comment]
Hi,

That's great thanks....this has solved the defaulting to the end of the list and I've also modified the round_sb class to do what I need.  Perfect!

As for the drop up rather than drop down thing I would say your suggestion is the way I would go.  Maybe doesn't need to be as much as 300px perhaps 150 or 200px difference. So the select box would need to be 200px below the middle of the screen before it goes up rather than down?  I think on my page it's a really tiny difference (15px approx) hense it seeming like odd behaviour.

Cheers,

Dan

**Comment by revsystems** [comment]
Great, glad that worked for you. I also just pushed the minified version of the script with these changes.

Look for the difference threshold implementation later today.

Thanks

**Comment by dwavell** [comment]
Thanks alot. Will keep an eye out and will get the minified version before the project goes live.

Dan
