### ISSUE TITLE
No Version Number?

### ISSUE THREAD

**Issue by mtrenker** [revsystems/jQuery-SelectBox#40]
Right now i have to make something up to not overwrite the older version. 
is there a reason why there are no version numbers?

**Comment by MaxPower15** [comment]
I haven't kept track of version numbers since every commit is technically a new version. There have been about 3 major revisions--those probably should have been labelled as such. Everything else is meant as bugfixes.

Do you think it's better to put a version number on the js file or on the containing folder?

**Comment by mtrenker** [comment]
well right now i want to try out the newest version because the one i'm working with currently has a bug (the "pageButtons" are prevented when i tab out of a selectbox, meaning i cant use space/backspace)

problem is, i cant just delete the old version because its used somewhere else and since there are no unique filenames and no versions i just had to use something like /sb/jquery.sb.js besides /selectbox/jquery.sb.js. using commit ids would just be confusing 

so yes i personally think a version number in the folder would be a good thing :)

edit: ups, wrong button, accidentally closed
