### ISSUE TITLE
Not applying with empty selectbox

### ISSUE THREAD

**Issue by tvdeyen** [revsystems/jQuery-SelectBox#8]
If I have an empty select box, then .sb() does not apply on this element.

**Comment by revsystems** [comment]
I'll take a look at this. What do you think expected behavior should be when a selectbox starts with no elements? Just show the arrow with no text display? I imagine it might actually throw a js error if nothing's in there--I never notice because I usually at least have something like <option disabled='disabled'>Select</option> in there.

**Comment by tvdeyen** [comment]
Just display the closed select box with empty text, but maybe with some default width and of course the arrow. The list of values does not open at all. That's the best behavior I think.
